---
# tasks file for install-name: adding a MySQL DB repo

- name: installing a MySQL DB on host
  apt:
    name: "{{ item }}"
    # name: ['mysql-client', 'mysql-server', 'python-pip', 'python-dev', 'libmysqlclient-dev']
          #    name: ['mysql-client', mysql-server, python-pip, python-dev, libmysqlclient-dev]
    state: present
    update_cache: true
  with_items:
  register: packages_installed
  with_items:
    - mysql-client
    - mysql-server
    - python-pip
    - python-dev
    - libmysqlclient-dev

- name: pip install PyMySQL
  pip:
    name: PyMySQL
  register: pip_installed

- name: Enable and started MySQL
  service:
    name: mysql
    state: started
    enabled: true

- name: .my.cnf adding a user and port
  template:
    src: root.conf.j2
    dest: ~/.my.cnf
    mode: 0600
    force: true
  register: client_conf_status
  when: packages_installed 

- name: server.cnf
  template:
    src: server.conf.j2
    dest: /etc/mysql/conf.d/server.cnf
    mode: 0644
    force: true
  when: packages_installed 
  register: server_conf_status

- name: Generate mysql credentials
  #- name:
  #  command: "mysql_secure_installation"
  mysql_user:
    name: user
    host: '{{ ansible_host }}'
    password: '{{ mysql_roni_pass}}'
  when: packages_installed

  #- name: Restart mysql to apply config
  #service:
  #  name: mysql
  #  state: restarted
  # when: client_conf_status.changed or server_conf_status.changed

#- name: Delete anonymous mysql user
#  mysql_user:
#    name: ""
#    state: absent

